### PR TITLE
fix(LookupCommand): show the guild of the invite, if present, disallow gdm invites

### LINKED ISSUE #64: [BUG HUNT] - Lookup command showing wrong guild
Screen Shot 2019-11-05 at 21 42 42
Screen Shot 2019-11-05 at 21 49 03

[Guild Info]()

## What went wrong
I tried to lookup The Dragon Maid Cult with k!lookup but it only showed info over the server i was using.

## Reproducing the bug

1. I typed kanna lookup
2. Put the invite code after it
3. It didn't show info over the server only the one i was in.

### PR DESCRIPTION
**Pull request by SpaceEEC**
This PR fixes #64 showing the actually resolved guild instead of the current one when an invite to a guild handled by the current shard is used.

This PR also disallows group dm channel invites to be used (not a guild after all).

### CODE REVIEW

File: src/commands/info/lookup.ts [hunk 1]
```diff
@@ -24,36 +25,53 @@ class LookupCommand extends Command
...
 		if (!code) return 'you have to give me an invite link or code!';
 
-		return this.client.fetchInvite(code)
-			.then((invite: Invite) => ([invite]))
-			.catch(() => 'I couldn\'t find a valid invite for this link or code.');
+		try
+		{
+			const invite: Invite = await this.client.fetchInvite(code);
+
+			if (!invite.guild) return 'this invite is not for a guild.';
```
Comment (wizardlink) [inline src/commands/info/lookup.ts:36]: I think `this invite is invalid!` would be more fitting than `this invite is not for a guild.`

File: src/commands/info/lookup.ts [hunk 2]
```diff
@@ -24,36 +25,53 @@ class LookupCommand extends Command
...
+
+			return [invite];
+		}
+		catch
+		{
+			return 'I could\'t find a valid invite for this link or code.';
```
Comment (wizardlink) [inline src/commands/info/lookup.ts]: Spelling mistake.

**Review by wizardlink — CHANGES_REQUESTED** [review]

File: src/commands/info/lookup.ts (hunk 1 above)
Comment (SpaceEEC) [reply src/commands/info/lookup.ts:36]: That would be misleading; the invite _is_ valid. It's just not an invite leading to a guild.

Comment (wizardlink) [reply src/commands/info/lookup.ts:36]: Alright I'll approve but, how would an invite be valid and not lead to a guild? Where else would it lead to?

**Review by wizardlink — APPROVED** [review]

File: src/commands/info/lookup.ts (hunk 1 above)
Comment (SpaceEEC) [reply src/commands/info/lookup.ts:36]: Group DMs

Comment (wizardlink) [reply src/commands/info/lookup.ts:36]: Oh yeah, that's a thing now. Good catch.
