### PR TITLE
fix(SaydCommand): do not delete already deleted message, handle unkown_message error

### LINKED ISSUE #77: [BUG HUNT] sayd errors out when prematurely deleting the message
## What went wrong

I deleted my message before kanna could when using 'kanna sayd', therefore making kanna produce an error message.

## Reproducing the bug

1. I wrote 'kanna sayd hello'
2. Then I immediately deleted my message saying 'kanna sayd hello', before kanna could.
image
image

### PR DESCRIPTION
**Pull request by SpaceEEC**
This PR fixes #77 by checking whether the message was already `deleted` and ignore `UNKNOWN_MESSAGE` errors due to race conditions with the previously mentioned property.

### CODE REVIEW

File: src/util/Util.ts [hunk 1]
```diff
@@ -218,3 +218,24 @@ const durationModifiers: { [key: string]: number } = {
  * @returns A duration in seconds
  */
 export const resolveDuration: (value: string) => number = _resolve.bind(null, durationRegex, durationModifiers);
+
+// Is there no builtin type for this?
+type ObjectValueType<T> = T extends { [key: string]: infer P } ? P : never
+
+/**
+ * High-order function catching certain DiscordAPIErrors and return them, rather than rethrowing them.
+ * @param errors Error codes to catch
```
Comment (wizardlink) [inline src/util/Util.ts:227]: No need to implicit the type as it's TS? I suppose you still should infer the type.

**Review by wizardlink — CHANGES_REQUESTED** [review]

File: src/util/Util.ts (hunk 1 above)
Comment (SpaceEEC) [reply src/util/Util.ts:227]: There is no type there, that's documentation.

Comment (wizardlink) [reply src/util/Util.ts:227]: [We're continuing the discussion through another platform]

**Review by wizardlink — APPROVED** [review]
