### PR TITLE
docs(commands): fix spelling mistakes

### LINKED ISSUE #57: [BUG HUNT] - Guildinfo command contains spelling mistake in usage
I was looking through help and I witnessed the 'guildinfo' spelt as 'guilinfo'.
I used kanna help, and moved to the page with guildinfo on it.
https://cdn.discordapp.com/attachments/299632639600492556/641363798267265026/unknown.png
don't know if this is the kind of link you want but here ^^
-CaptMU#2702

### LINKED ISSUE #58: [BUG HUNT] - DoIt command has invalid usage
Screen Shot 2019-11-05 at 21 06 46

 I did k!help and on page 3 it said kanna doit for the k!dance comment

1. I typed k!help
2. Then pressed on the arrow 2 times
3. Then i saw "Kanna doit" above the k!dance command.

-Digit!#5125

### LINKED ISSUE #59: [BUG HUNT] - Blocklist command has incorrect desc., example, and usage
Screen Shot 2019-11-05 at 21 16 00
Screen Shot 2019-11-05 at 21 15 58

## What went wrong
It says k!block twice while kanna blocklist is k!blocklist and kanna block is k!block

1. I did k!help
2. scrolled through the pages
3. saw it said k!block under kanna blocklist instead of k!blocklist

-Digit#5125

### LINKED ISSUE #60: [BUG HUNT] - Gramatically incorrect 's in the help command
image

Kiss's should be kiss'

## Reproducing the bug

I did kanna help kiss.
I saw a mistake.
-CaptMU#2702

### LINKED ISSUE #61: [BUG HUNT] - osuuser command has wrong command name in usage
Screen Shot 2019-11-05 at 21 30 03
Screen Shot 2019-11-05 at 21 30 14
## What went wrong

I was trying to lookup my osu user but k!osucommand did not work but k!osuuser did work.

1. I looked in k!help
2. Tried to use k!osucommand
3. It didn't work
4. Tried k!osuuser and it did work

-Digit#5125
[edit] k!help osucommand said osu command didnt exist.
Screen Shot 2019-11-05 at 21 37 24

### LINKED ISSUE #66: [BUG HUNT] Wrong command
## Information
v4.5.1
#### Kanna Kobayashi

Screen Shot 2019-11-07 at 18 54 40

## What went wrong

I typed "k!help avatar" and it said kanna image between aliases when kanna image is a whole different command.

## Reproducing the bug

1. I typed "k!help avatar"
2. It said "kanna image" between aliases

-Digit#5125

### PR DESCRIPTION
**Pull request by wizardlink**
This fixes all the following issues:

resolved #57
resolved #58
resolved #59
resolved #60
resolved #61
resolved #66

### CODE REVIEW

File: src/commands/common/help.ts [hunk 1]
```diff
@@ -131,7 +131,7 @@ class HelpCommand extends Command implements IResponsiveEmbedController
 		}
 
 		const embed: MessageEmbed = MessageEmbed.common(message, authorModel)
-			.setAuthor(`${titleCase(command.name)}'s Info`, this.client.user!.displayAvatarURL())
+			.setAuthor(`${titleCase(command.name)}${/s$/.test(command.name) ? '\'' : '\'s'} Info`, this.client.user!.displayAvatarURL())
```
Comment (SpaceEEC) [inline src/commands/common/help.ts:134]:
```suggestion
			.setAuthor(`${titleCase(command.name)}'${command.name.endsWith('s') ? '' : 's'} Info`, this.client.user!.displayAvatarURL())
```

**Review by SpaceEEC — APPROVED** [review]
